name: DoomEmacs

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/ci.yml'
      - 'assets/**'
      - 'Dockerfile'
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync-and-release:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Deps
      run: |
        pacman-key --init
        pacman-key --populate archlinux
        pacman -Syu emacs git tar zstd --noconfirm --quiet

    - name: sync doom source
      run: |
        echo "BASE_DIR=$(pwd)" >> $GITHUB_ENV
        git clone https://github.com/doomemacs/doomemacs.git ~/.config/emacs
        mv doom ~/.config/
        echo "Synced on: $(date)" > date.txt
        ~/.config/emacs/bin/doom install --no-env --doomdir ~/.config/doom --emacsdir ~/.config/emacs
        curl https://raw.githubusercontent.com/omansh-krishn/crave-aosp-archlinux-docker-image/refs/heads/main/assets/getdoom > getdoom; chmod +x getdoom

    - name: tar it
      run: |
        cd ~/.config
        tar -I 'zstd -T0 -19' -cf doom.tar.zst doom emacs
        mv doom.tar.zst ${{ env.BASE_DIR }}/

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          name: 'doomemacs'
          tag_name: 'doomemacs'
          token: ${{ secrets.PAT }}
          files: |
            ${{ env.BASE_DIR }}/doom.tar.zst
            ${{ env.BASE_DIR }}/getdoom
          body_path: ${{ env.BASE_DIR }}/date.txt
